definitions:
  configs.Config:
    properties:
      cache:
        properties:
          bangumi_cache_hour:
            type: integer
          mikan_cache_hour:
            type: integer
          themoviedb_cache_hour:
            type: integer
        type: object
      category:
        type: string
      client:
        properties:
          check_time_second:
            type: integer
          connect_timeout_second:
            type: integer
          retry_connect_num:
            type: integer
        type: object
      data_path:
        type: string
      default:
        properties:
          tmdb_fail_skip:
            type: boolean
          tmdb_fail_use_first_season:
            type: boolean
          tmdb_fail_use_title_season:
            type: boolean
        type: object
      download:
        properties:
          allow_duplicate_download:
            type: boolean
          ignore_size_max_kb:
            type: integer
          queue_delay_second:
            type: integer
          queue_max_num:
            type: integer
          seeding_time_minute:
            type: integer
        type: object
      feed:
        properties:
          delay_second:
            type: integer
          multi_goroutine:
            properties:
              enable:
                type: boolean
              goroutine_max:
                type: integer
            type: object
          update_delay_minute:
            type: integer
        type: object
      filter:
        properties:
          javascript:
            items:
              type: string
            type: array
        type: object
      key:
        properties:
          themoviedb:
            type: string
        type: object
      path:
        properties:
          db_file:
            type: string
          log_file:
            type: string
          temp_path:
            type: string
        type: object
      proxy:
        properties:
          enable:
            type: boolean
          url:
            type: string
        type: object
      request:
        properties:
          retry_num:
            type: integer
          retry_wait_second:
            type: integer
          timeout_second:
            type: integer
        type: object
      save_path:
        type: string
      tag:
        type: string
      update_delay_second:
        type: integer
      version:
        type: string
      webapi:
        properties:
          access_key:
            type: string
          host:
            type: string
          port:
            type: integer
        type: object
    type: object
  models.ConfigResponse:
    properties:
      config:
        $ref: '#/definitions/configs.Config'
      data:
        type: string
    type: object
  models.PluginConfigUploadRequest:
    properties:
      data:
        description: base64格式的文本数据
        type: string
      name:
        description: 插件文件名
        type: string
    required:
    - data
    - name
    type: object
  models.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  models.SelectEpRequest:
    properties:
      ep_links:
        items:
          type: string
        type: array
      is_select_ep:
        default: false
        type: boolean
      rss:
        properties:
          url:
            type: string
        required:
        - url
        type: object
      source:
        type: string
    required:
    - rss
    - source
    type: object
info:
  contact: {}
  license:
    name: MIT
    url: https://www.mit-license.org/
  termsOfService: https://github.com/wetor/AnimeGo
paths:
  /api/config:
    get:
      consumes:
      - application/json
      description: 将待下载项组合成rss发送给AnimeGo
      parameters:
      - default: all
        description: |-
          Key 使用目录方式获取指定yaml key内容
            [暂不支持] 如 setting/save_path, advanced/download/queue_max_num
            all 获取所有配置项，json格式
            raw 获取所有配置项，yaml文本格式
            comment 获取所有配置项的注释文本
        in: query
        name: key
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.ConfigResponse'
              type: object
        "300":
          description: Multiple Choices
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取设置
      tags:
      - config
  /api/plugin/config:
    get:
      consumes:
      - application/json
      description: |-
        从AnimeGo中获取当前插件的配置
        插件名为不包含 'plugin' 的路径
        插件名可以忽略'.js'后缀；插件名也可以使用上层文件夹名，会自动寻找文件夹内部的 'main.js' 或 'plugin.js'
        如传入 'test'，会依次尝试寻找 'plugin/test/main.js', 'plugin/test/plugin.js', 'plugin/test.js'
      parameters:
      - description: 插件信息
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "300":
          description: Multiple Choices
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取插件配置
      tags:
      - plugin
    post:
      consumes:
      - application/json
      description: |-
        将当前插件的配置发送给AnimeGo并保存
        插件名为不包含 'plugin' 的路径
        插件名可以忽略'.js'后缀；插件名也可以使用上层文件夹名，会自动寻找文件夹内部的 'main.js' 或 'plugin.js'
        如传入 'test'，会依次尝试寻找 'plugin/test/main.js', 'plugin/test/plugin.js', 'plugin/test.js'
      parameters:
      - description: 插件信息，data为base64编码后的json文本
        in: body
        name: plugin
        required: true
        schema:
          $ref: '#/definitions/models.PluginConfigUploadRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "300":
          description: Multiple Choices
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: 发送插件配置
      tags:
      - plugin
  /api/rss:
    post:
      consumes:
      - application/json
      description: 将待下载项组合成rss发送给AnimeGo
      parameters:
      - description: 组合的rss信息
        in: body
        name: rss
        required: true
        schema:
          $ref: '#/definitions/models.SelectEpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "300":
          description: Multiple Choices
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: 发送下载项
      tags:
      - plugin
  /ping:
    get:
      consumes:
      - application/json
      description: Pong
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: Ping
      tags:
      - web
  /sha256:
    get:
      consumes:
      - application/json
      description: SHA256计算
      parameters:
      - description: 原文本
        in: query
        name: access_key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: SHA256计算
      tags:
      - web
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Access-Key
    type: apiKey
swagger: "2.0"
